### PR TITLE
Add support for U2F based devices

### PR DESCRIPTION
**Pull request by jonasschnelli**
This PR detected devices that use the communication protocol based on the U2F specification and communicates with them according to this protocol.

The `dbb-cli` has two new calls, `u2f-on` and `u2f-off` (currently not possible to enable/disable U2F in the GUI).

Requires device firmware 2.1.0

### CODE REVIEW

**Comment by saleemrashid** [comment]
@jonasschnelli I've been meaning to ping you about the missing `htonl` header 😆

**Comment by jonasschnelli** [comment]
@saleemrashid: about the HID locking issue. Yes. We should probably look into it, though I think it's reasonable to block during certain command chains. Example: during the creation of the wallet, multiple interactions with the device are done (yes, stateless), but still, during this time, we probably don't want to add the risk of interfering from other interface types (like U2F).

But yes, during the pure idle process, we should release the HID lock.

**Comment by saleemrashid** [comment]
> We should probably look into it, though I think it's reasonable to block during certain command chains.

I fully agree.

However, I think that adding a separate interface for U2F is a good idea. There is an abundance of USB endpoints so, as far as I know, those are not a limiting factor.

**Comment by jonasschnelli** [comment]
* Added support for devices where no password has been set yet.
* Always close/reopen the HID channel

**Pull request merged**
