### PR TITLE
Linux udev rule check at startup

### PR DESCRIPTION
**Pull request by jonasschnelli**

### CODE REVIEW

**Comment by saleemrashid** [comment]
@jonasschnelli Can this be conditionally compiled? I've packaged this application for Arch Linux, and the udev rules are elsewhere, so I would like to be able to disable this check completely.

**Comment by jonasschnelli** [comment]
I though about adding a compile option. But, since there is a persisted "don't warn me again" option, I don't think it's worth the added complexity.

**Comment by saleemrashid** [comment]
Well, it's bad UX because this might make people think my package is broken. I could patch the source code but it shouldn't be difficult to add a compile option.

I'll have a go at it when I get time.

**Comment by jonasschnelli** [comment]
Added @saleemrashid's https://github.com/jonasschnelli/dbb-app/pull/15
Thanks!

**Pull request merged**
